---
name: Pre-Commit Hooks

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: pre-commit-hooks-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.14'

jobs:
  pre-commit:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv dependencies
        env:
          UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache
        run: uv sync --locked --all-groups

      - name: Run prek
        id: run-pch
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        continue-on-error: true
        with:
          prek-version: 0.3.11
          extra-args: --all-files
          cache: true

      - name: Commit Modified Files
        if: steps.run-pch.outcome == 'failure'
        env:
          REF: ${{ github.event.pull_request.head.ref }}
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        # yamllint disable rule:line-length
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "No changes to commit, something else must have gone wrong. Check previous step for more information."
            exit 1
          fi

          git config --global user.name "worgarside-dev"
          git config --global user.email "worgarside.dev@gmail.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git add .

          git commit -m "style: Fixes from prek hooks" --no-verify

          git push origin "${REF}"

          UNCOMMITTED_FILES=$(git status -s | awk '{print $2}')

          if [[ -n "$UNCOMMITTED_FILES" ]]; then
            echo -e "\`\`\`\n${UNCOMMITTED_FILES}\n\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
            exit 1
          fi
        # yamllint enable rule:line-length
